### PR TITLE
Support V6

### PR DESCRIPTION
**Pull request by ascrutae**
I had build a demo to test this PR. There are two projects in this demo, one is write by Java and the other's is Node.js.

Here is the topology :
wx20190207-222804 2x

Here is the trace:
wx20190207-222824 2x

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why the trace view looks strange, the caller time is much less than callee. Is that caused by async mode? Do you have any way to improve that?

**Comment by ascrutae** [comment]
yes, it is async mode.

**Comment by wu-sheng** [comment]
If that span keeps in this way, the response time looks like too short, and not real, especially don't include the dependency service invoke time. Why do you stop the span so early?

I know this is a separated issue from v6 protocol, but I think this is important.

**Comment by wu-sheng** [comment]
If you look the service and endpoint metric page, the response avg and p99 are all not right.

**Comment by ascrutae** [comment]
The Node.js project is async request and it returns value without wait the response of the java project. and I had adjust the demo that the Node.js project wait the response of the java project. 

Here is the trace graph:
wx20190207-234616 2x

**Review by wu-sheng — APPROVED** [review]
The new trace view makes sense to me.

**Pull request merged**
